version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - VERSION=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed 's/branch\///g')
      - sh $CODEBUILD_SRC_DIR/build-config/sns_util.sh "START" "$VERSION"
      - npm config set unsafe-perm true
      - npm config set always-auth true
      - npm config set scripts-prepend-node-path true
      - npm config set registry=https://registry.npmjs.com/
      - npm config set //registry.npmjs.com/:_authToken=$NPM_TOKEN
      - npm whoami
      - npm config list
      - echo "Installing yarn Packages..."
      - yarn bootstrap
      - echo "Yarn build and publishing to NPM"
      - npm run release -- --no-git --no-github.release --ci >>/tmp/build.log 2>&1 || { cat /tmp/build.log ; exit 1 ; }
      - VERSION=$(grep -A1 Changelog /tmp/build.log | tail -n 1 | cut -d'[' -f2 | cut -d']' -f1)
      - NPM_VERSION=$(npm show @chargebee/react-native-chargebee version)
      - echo $NPM_VERSION | grep -q $VERSION || { echo "Version between Build and NPM not matched" ; exit 1 ; }
    finally:
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ]; then
            sh $CODEBUILD_SRC_DIR/build-config/sns_util.sh "FAILED" "$VERSION"
        else
            sh $CODEBUILD_SRC_DIR/build-config/sns_util.sh "SUCCESS" "$VERSION"
        fi
